org: lucasaliaga
service: api-alumnos-rds

provider:
  name: aws
  runtime: python3.13
  memorySize: 1024
  timeout: 20
  iam:
    role: arn:aws:iam::2148-1714-8898:role/LabRole
  environment:
    SECRET_NAME: alumnos_${sls:stage}_secret
    DB_NAME: ${sls:stage}

functions:
  listar:
    handler: ListarAlumnos.lambda_handler
    package:
      include:
        - ./**
    events:
      - http:
          path: /alumnos/listar
          method: get
          cors: true
          integration: lambda
